# DATABASE CONFIGURATION
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

#SECURITY, AUTHORIZATION
jwt:
  secret:
    key: ${MEDICAL_SECRET_KEY}

# VALIDATION
server:
  error:
    include-message: always
#    include-binding-errors: always